### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LoggingMixIn'

### ISSUE THREAD

**Issue by GavinDmello** [etactica/mqtt-malaria#39]
Hi,
I'm facing this issue when running malaria subscribe

```
OS : Ubuntu 16.04
fusepy version : 2.0.4
```

**Comment by karlp** [comment]
looks like an installaiton problem.  please try reading the steps in https://github.com/remakeelectric/mqtt-malaria/issues/20

**Comment by karlp** [comment]
Closing as no further updates, feel free to re-open if you have updated information.
