### ISSUE TITLE
No option to provide username and password in Malaria

### ISSUE THREAD

**Issue by anandxp** [etactica/mqtt-malaria#41]
Went through the arguments for publishing MQTT messages in Malaria , But didnt find any option to provide username and password in Malaria.

Given below supported arguments

malaria publish [-h] [-c CLIENTID] [-H HOST] [-p PORT]
                            [-q {0,1,2}] [-n MSG_COUNT] [-s MSG_SIZE] [-t]
                            [-T MSGS_PER_SECOND] [-P PROCESSES]

**Comment by karlp** [comment]
Correct, it wasn't ever needed for the testing this was developed for, and it's not been contributed by anyone since.

**Comment by anandxp** [comment]
Hi @karlp 
I am closing this issue
