### ISSUE TITLE
How to run the tool on Windows 10?

### ISSUE THREAD

**Issue by kulkarniatharv** [etactica/mqtt-malaria#46]
I have installed python2, fusepy and all necessary tools mentioned in the README file and also by following [this](https://www.thelinuxfaq.com/491-how-to-install-and-testing-mqtt-using-mqtt-malaria-on-ubuntu).

When I try to execute this in powershell, `./malaria publish -P 100 -n 1000 -H 192.168.2.20  -s 100  -T 1 -q 0` this is what pops up(image below)
![image](https://user-images.githubusercontent.com/15829308/123320490-73640700-d54f-11eb-8d9e-aa09f8192333.png)

How can I test the broker on windows using this tool?

**Comment by karlp** [comment]
I'm afraid I have absolutely no idea how to run things on windows, or powershell.  I would recommend working out whether other python process work, and do the same thing here.  It's "just" a python app.  But there's nothing I can do for you I'm afraid.
